CREATE DATABASE CONTACT_FORM_DB;

USE CONTACT_FORM_DB;

CREATE TABLE CONTACT_SUBMISSIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    MESSAGE TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);